Rewrite CI pipeline to E2E test the ethsecp256k1 key scheme and accounts.

diff --git a/scripts/setup-chains b/scripts/setup-chains
--- a/scripts/setup-chains
+++ b/scripts/setup-chains
@@ -31,10 +31,10 @@ CHAIN_0_ID="$1"
 CHAIN_1_ID="$2"
 CHAIN_2_ID="$3"
 
-GAIA_DATA="$(pwd)/data"
+INJECTIVE_DATA="$(pwd)/data"
 
 # Ensure user understands what will be deleted
-if [[ -d $GAIA_DATA ]] && [[ ! "$3" == "skip" ]]; then
+if [[ -d $INJECTIVE_DATA ]] && [[ ! "$3" == "skip" ]]; then
   echo "WARNING: $0 will DELETE the '$(pwd)/data' folder."
   read -p "> Do you wish to continue? (y/n): " -n 1 -r
   echo
@@ -43,25 +43,25 @@ if [[ -d $GAIA_DATA ]] && [[ ! "$3" == "skip" ]]; then
   fi
 fi
 
-# Ensure gaiad is installed
-if ! [ -x "$(which gaiad)" ]; then
-  echo "Error: gaiad is not installed. Try running 'make build-gaia'" >&2
+# Ensure injectived is installed
+if ! [ -x "$(which injectived)" ]; then
+  echo "Error: injectived is not installed. Try running 'make build-injective'" >&2
   exit 1
 fi
 
 # Display software version
-echo "GAIA VERSION INFO: $(gaiad version --log_level info)"
+echo "INJECTIVE VERSION INFO: $(injectived version --log-level info)"
 
 # Delete data from old runs
-echo "Deleting $GAIA_DATA folder..."
-rm -rf "$GAIA_DATA"
+echo "Deleting $INJECTIVE_DATA folder..."
+rm -rf "$INJECTIVE_DATA"
 
-# Stop existing gaiad processes
-killall gaiad &> /dev/null || true
+# Stop existing injectived processes
+killall injectived &> /dev/null || true
 killall akash &> /dev/null || true
 
-echo "Generating gaia configurations..."
-mkdir -p "$GAIA_DATA" && cd "$GAIA_DATA" && cd ../
+echo "Generating injective configurations..."
+mkdir -p "$INJECTIVE_DATA" && cd "$INJECTIVE_DATA" && cd ../
 
 ONE_CHAIN="$(dirname "$0")/one-chain"
 
@@ -73,20 +73,20 @@ CHAIN_0_GRPC_PORT=9090
 CHAIN_1_GRPC_PORT=9091
 CHAIN_2_GRPC_PORT=9092
 
-CHAIN_0_SAMOLEANS=100000000000
-CHAIN_1_SAMOLEANS=100000000000
-CHAIN_2_SAMOLEANS=100000000000
+CHAIN_0_INJ=100000000000
+CHAIN_1_INJ=100000000000
+CHAIN_2_INJ=100000000000
 
-"$ONE_CHAIN" gaiad "$CHAIN_0_ID" ./data $CHAIN_0_RPC_PORT 26656 6060 $CHAIN_0_GRPC_PORT $CHAIN_0_SAMOLEANS
-"$ONE_CHAIN" gaiad "$CHAIN_1_ID" ./data $CHAIN_1_RPC_PORT 26556 6061 $CHAIN_1_GRPC_PORT $CHAIN_1_SAMOLEANS
+"$ONE_CHAIN" injectived "$CHAIN_0_ID" ./data $CHAIN_0_RPC_PORT 26656 6060 $CHAIN_0_GRPC_PORT $CHAIN_0_INJ
+"$ONE_CHAIN" injectived "$CHAIN_1_ID" ./data $CHAIN_1_RPC_PORT 26556 6061 $CHAIN_1_GRPC_PORT $CHAIN_1_INJ
 
 if [ -n "$CHAIN_2_ID" ]; then
-  "$ONE_CHAIN" gaiad "$CHAIN_2_ID" ./data $CHAIN_2_RPC_PORT 26456 6062 $CHAIN_2_GRPC_PORT $CHAIN_2_SAMOLEANS
+  "$ONE_CHAIN" injectived "$CHAIN_2_ID" ./data $CHAIN_2_RPC_PORT 26456 6062 $CHAIN_2_GRPC_PORT $CHAIN_2_INJ
 fi
 
-[ -f "$GAIA_DATA/$CHAIN_0_ID.log" ] && echo "$CHAIN_0_ID initialized. Watch file $GAIA_DATA/$CHAIN_0_ID.log to see its execution."
-[ -f "$GAIA_DATA/$CHAIN_1_ID.log" ] && echo "$CHAIN_1_ID initialized. Watch file $GAIA_DATA/$CHAIN_1_ID.log to see its execution."
+[ -f "$INJECTIVE_DATA/$CHAIN_0_ID.log" ] && echo "$CHAIN_0_ID initialized. Watch file $INJECTIVE_DATA/$CHAIN_0_ID.log to see its execution."
+[ -f "$INJECTIVE_DATA/$CHAIN_1_ID.log" ] && echo "$CHAIN_1_ID initialized. Watch file $INJECTIVE_DATA/$CHAIN_1_ID.log to see its execution."
 
 if [ -n "$CHAIN_2_ID" ]; then
-  [ -f "$GAIA_DATA/$CHAIN_2_ID.log" ] && echo "$CHAIN_2_ID initialized. Watch file $GAIA_DATA/$CHAIN_2_ID.log to see its execution."
+  [ -f "$INJECTIVE_DATA/$CHAIN_2_ID.log" ] && echo "$CHAIN_2_ID initialized. Watch file $INJECTIVE_DATA/$CHAIN_2_ID.log to see its execution."
 fi
